# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: migration_payload.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'migration_payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17migration_payload.proto\x12\x04main\"?\n\x10MigrationPayload\x12+\n\x0eotp_parameters\x18\x01 \x03(\x0b\x32\x13.main.OtpParameters\"!\n\rOtpParameters\x12\x10\n\x08raw_data\x18\x01 \x01(\x0c\x42\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'migration_payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_MIGRATIONPAYLOAD']._serialized_start=33
  _globals['_MIGRATIONPAYLOAD']._serialized_end=96
  _globals['_OTPPARAMETERS']._serialized_start=98
  _globals['_OTPPARAMETERS']._serialized_end=131
# @@protoc_insertion_point(module_scope)
