# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: migration_payload.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'migration_payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17migration_payload.proto\x12\x04main\"?\n\x10MigrationPayload\x12+\n\x0eotp_parameters\x18\x01 \x03(\x0b\x32\x13.main.OtpParameters\"\x8f\x01\n\rOtpParameters\x12\x10\n\x08raw_data\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06issuer\x18\x03 \x01(\t\x12\x11\n\talgorithm\x18\x04 \x01(\t\x12\x0e\n\x06\x64igits\x18\x05 \x01(\x05\x12\x0e\n\x06period\x18\x06 \x01(\x03\x12\x1b\n\x04type\x18\x07 \x01(\x0e\x32\r.main.OtpType*I\n\x07OtpType\x12\x18\n\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rOTP_TYPE_HOTP\x10\x01\x12\x11\n\rOTP_TYPE_TOTP\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'migration_payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OTPTYPE']._serialized_start=244
  _globals['_OTPTYPE']._serialized_end=317
  _globals['_MIGRATIONPAYLOAD']._serialized_start=33
  _globals['_MIGRATIONPAYLOAD']._serialized_end=96
  _globals['_OTPPARAMETERS']._serialized_start=99
  _globals['_OTPPARAMETERS']._serialized_end=242
# @@protoc_insertion_point(module_scope)
